apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: whwp4151/spring-cicd-k8s-demo:develop-39
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: develop
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3

  strategy:
    canary:
      stableService: my-app-stable-service
      canaryService: my-app-canary-service

      trafficRouting:
        nginx:
          stableIngress: my-app-ingress
          canaryIngress: my-app-ingress

      steps:
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100