apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: whwp4151/spring-cicd-k8s-demo:develop-27
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: develop
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
  strategy:
    canary:
      stableService: my-app-stable-service
      canaryService: my-app-canary-service
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100